definitions:
  domain.Todo:
    properties:
      completed:
        type: boolean
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  domain.TodoRequest:
    properties:
      completed:
        type: boolean
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /todos:
    post:
      consumes:
      - application/json
      parameters:
      - description: Todo object to be created
        in: body
        name: domain.Todo
        required: true
        schema:
          $ref: '#/definitions/domain.TodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Todo created successfully
          schema:
            $ref: '#/definitions/domain.Todo'
        "400":
          description: 'Bad Request: invalid request data'
          schema:
            type: string
        "422":
          description: 'Unprocessable Entity: "invalid json body'
          schema:
            type: string
      summary: Create a new todo item.
      tags:
      - todos
swagger: "2.0"
